spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
      add-mappings: false
  profiles:
    active: "dev"
logging:
  config: classpath:log4j2-dev.xml

#dev
---

spring:
  profiles: dev

server:
  port: 9090
  connection-timeout: 5000
